version: '3.9'
services:
  web-client:
    build:
      context: .
      dockerfile: ./infrastructure/Dockerfile
    environment:
      - NODE_ENV=production
      - VOTE_API_BASE_URL=http://vote-api:8080
    ports:
      - "3000:3000"
    depends_on:
      - vote-api
    networks:
      - app-network
    volumes:
      - ./web-client:/usr/src/app

  vote-api:
    build:
      context: .
      dockerfile: ./infrastructure/API/Dockerfile
    environment:
      - PG_URL=postgres://postgres:postgres@db:5432/vote_db?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./vote-api:/usr/src/app


  docs:
    build:
      context: .
      dockerfile: ./infrastructure/Doc/Dockerfile
    ports:
      - "4000:3000"
    networks:
      - app-network
    volumes:
      - ./docs:/usr/src/app

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vote_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
