version: '3.9'
services:
  web-client:
    build:
      context: ./web-client
      dockerfile: ../infrastructure/Dockerfile
      target: production
    environment:
      - NODE_ENV=production
      - VOTE_API_BASE_URL=http://vote-api:8080
    ports:
      - "3000:3000"
    depends_on:
      - vote-api
    networks:
      - app-network

  vote-api:
    build:
      context: ./vote-api
      dockerfile: ../infrastructure/API/Dockerfile
      target: production
    environment:
      - PG_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  docs:
    build:
      context: ./docs
      dockerfile: ../infrastructure/Doc/Dockerfile
      target: production
    ports:
      - "4000:4000"
    networks:
      - app-network

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./infrastructure/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web-client
      - docs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
